const Datos =[
    {id:'1',
    nombre:'Heladera Samsung',
    img:'https://imgur.com/txchIVL.jpg',
    precio: 100000,
    stock:"6",
    categoria:"heladeras"},
    {id:'2',
    nombre:'Heladera Gafa',
    img:'https://imgur.com/Pywht1j.jpg',
    precio: 40000,
    stock:"15",
    categoria:"heladeras"},
     {id:'3',
    nombre:'Microondas BGH',
    img:'https://www.megatone.net/Images/Articulos/zoom2x/32/COC2020BGH.jpg',
    precio: 120000,
    stock:"7",
    categoria:"microondas"},
     {id:'4',
    nombre:'Microondas Sansei',
    img:'https://imgur.com/r67gFiZ.jpg',
    precio: 30000,
    stock:"3",
    categoria:"microondas"},
    ];

export default Datos